default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: my_andromeda_app_development

production:
# On utilise les variables que TU as définies dans ton environnement EB
  primary: &default_prod
    adapter: postgresql
    encoding: unicode
    pool: 5
    # On utilise la valeur en dur de ton fichier original, car tu n'as pas de variable DB_NAME
    database: my_andromeda_app_production 
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    

  # On dit aux autres gems "Solid" d'utiliser cette même config
  solid_queue:
    <<: *default_prod 

  solid_cache:
    <<: *default_prod 

  cable:
    <<: *default_prod 