default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: my_andromeda_app_development

production:

  primary: &default_prod
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: my_andromeda_app_production 
    username: <%= ENV['DB_USERNAME'] %>
    password: <%= ENV['DB_PASSWORD'] %>
    host: <%= ENV['DB_HOST'] %>
    port: 5432

    
  queue:
    <<: *default_prod

  cache:
    <<: *default_prod

  cable:
    <<: *default_prod